[project]
name = "blog-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fileorganize>=0.0.4",
    "ipython>=9.17.1",
    "jupyter>=1.1.1",
    "jupytext>=1.19.5",
    "librosa>=1.0.0",
    "nbformat>=5.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "phonlab>=0.0.63",
    "plotly>=7.1.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "torchaudio>=2.11.0",
    "tqdm>=4.70.1",
    "transformers>=5.17.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "ipython>=9.17.1",
    "jupyter>=1.1.1",
    "jupytext>=1.19.5",
    "pright>=0.0.1",
    "pyright>=1.1.414",
    "ruff>=0.16.9",
]
